trigger:
  branches:
    include: [ main ]

variables:
  registry: docker.io/pavlink1
  imageName: todo-app-denshi
  tag: $(Build.BuildId)

stages:
  - stage: Test
    displayName: 'Run Tests'
    jobs:
      - job: RunTests
        pool: { name: 'Default' }
        steps:
          - checkout: self
          - task: NodeTool@0
            inputs: { versionSpec: '20.x' }
          - script: |
              npm ci
              npm test
            displayName: 'Install & Run Tests'

  - stage: Build
    displayName: 'Build Image'
    dependsOn: Test
    jobs:
      - job: BuildImage
        pool: { name: 'Default' }
        steps:
          - checkout: self
          - script: |
              docker build -t $(registry)/$(imageName):$(tag) .
            displayName: 'Build Docker Image'

  - stage: Push
    displayName: 'Push to Docker Hub'
    dependsOn: Build
    jobs:
      - job: PushImage
        pool: { name: 'Default' }
        steps:
          - checkout: self
          - task: Docker@2
            displayName: 'Login to Docker Hub'
            inputs:
              command: login
              containerRegistry: dockerhub-connection
          - script: |
              docker push $(registry)/$(imageName):$(tag)
              docker tag $(registry)/$(imageName):$(tag) $(registry)/$(imageName):latest
              docker push $(registry)/$(imageName):latest
            displayName: 'Push tags (build-id & latest)'
